Enhancement MPPT metrics added
ccremer/fronius-exporter pull request #42
Opened 2021-08-05 13:52 UTC by sveba

## Summary
Adds MPPT metrics. MPPT metrics are archived by the fronius inverter every 5 mins. 

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `fix`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] Update documentation.
- [x] Update tests.

2021-08-06 07:38 UTC, ccremer commented
Hi!
Thanks for the PR. I'll try to review it today or in the weekend.

2021-08-06 23:04 UTC, ccremer requested changes
Good work so far! 🎉 
I think it could be even more improved for both user and maintainers though.

2021-08-09 06:09 UTC, sveba commented on metrics.go
>  		scrapeErrorCount.Add(1)
Agree

2021-08-09 06:10 UTC, sveba commented on metrics.go
>  	} else {
Agree. will do

2021-08-09 06:13 UTC, sveba commented on pkg/fronius/symo.go
> +	}
IMHO: I would prefer to not rely on array for mapping and referring the urls.  Thats why I created additional variable. Feel free to correct me, as I'm still very green in Go coming from JS and Java world :)

2021-08-09 06:14 UTC, sveba commented on pkg/fronius/symo.go
>  			Header: options.Headers,
See previous comment

2021-08-09 06:25 UTC, sveba commented on pkg/fronius/symo.go
> +	log.WithField("url", *c.requestArchiveData.URL).Debug("URL")
1. Moving the logic out- OK
2. q.Set() was the first approach that I tried. The problem was the encoding after that. The fronius API didn't like the encoding of the date-params and delivered wrong timespan.  At least mine inverter. Maybe you ca try with yours.
3. The 5 mins timespan is hardcoded and the Fronius API delivers the values in 5 mins spans. There is the possibility to query for a bigger timespan and than the values map has multiple elements. Like this:
```
{
  "0": 200,
  "300": 212,
  "600": 140
  ...
}```
As this is prometheus exporter, we need only the value at the time of the scraping. Thats why I'm calculating the rounded timespan.

2021-08-09 09:01 UTC, sveba commented on pkg/fronius/symo.go
> +	}
All parameters are necessary. About the values: I have only one inverter and one smart meter. My approach is always to cover the 95% of the use cases and if someone has additional different use case, than ask for test data (like json response) and work with it. 
But this is your baby, so you can decide the approach. I just don't feel comfortable to implement something based on assumptions :)

2021-08-09 09:07 UTC, ccremer commented on pkg/fronius/symo.go
> +	log.WithField("url", *c.requestArchiveData.URL).Debug("URL")
2) Ok. I would prefer it if you'd at least fmt.Sprintf() instead of string concatenation
3) Okay lets keep the 5 minutes.

2021-08-09 09:13 UTC, ccremer commented on pkg/fronius/symo.go
> +	}
Hm, agreed arrays are kinda clumsy. I would be open for a map approach (prosa):
```go
var apiUrls = map[string]*url.URL{
  "powerflow": parseUrlOrDie("/solar_api/v1/GetPowerFlowRealtimeData.fcgi"),
  "archive": parseUrlOrDie("/solar_api/v1/GetArchi..."),
}

func parseUrlOrDie(url string) *url.URL {
u, err := url.Parse(options.URL + partial)
	    if err != nil {
		    panic(err)
	    }
	    return u
}

func ... {
  ...

		requestArchiveData: &http.Request{
			URL:    apiUrls["archive"],
}
```

2021-08-10 06:29 UTC, sveba commented on pkg/fronius/symo.go
> +	}
Great, had the same idea with the const. Otherwise a little bit different solution. I hope it fits your QA :)

2021-08-10 08:01 UTC, ccremer reviewed
2 things that came to mind: Right now the `timeout` option is applied to both requests. Meaning a timeout of 5 seconds could potentially end up in a scrape of 10 seconds. If we have further Data to scrape, 15 seconds etc. It should be at least documented what this means.

However, thinking even further, it's probably a good idea to make the requests in parallel. That should end up in faster scraping. A little more care needs to be given regarding error handling, in order to present only 1 error to the user, I'd propose to add https://github.com/hashicorp/go-multierror into the mix: Each fatal scrape error can be combined into one and it nicely displays multiple occurred errors. 

I would be fine with doing this in a second step in a separate PR. If you would be interested in doing this, I would also delay a release until we have parallelization.

2021-08-10 08:01 UTC, ccremer commented on pkg/fronius/symo.go
> +	}
Yep, your solution is better than my braindump. I'm happy with that

2021-08-10 08:38 UTC, sveba commented on pkg/fronius/symo.go
> +			URL:    nil,
Done

2021-08-10 08:38 UTC, sveba commented on metrics.go
> +	sitePowerPhotovoltaicsGauge.Set(powerFlowData.Site.PowerPhotovoltaic)
Done

2021-08-10 08:38 UTC, sveba commented on cfg/types.go
> +			PowerFlowEnabled: true,
done

2021-08-10 08:39 UTC, sveba commented on Makefile
> +#build: export GOOS = linux
accident, fixed

2021-08-10 08:39 UTC, sveba commented
> I would be fine with doing this in a second step in a separate PR. If you would be interested in doing this, I would also delay a release until we have parallelization.

Agree, but additional PR would be my choice

2021-08-10 09:48 UTC, ccremer commented on Makefile
> +#build: export GOOS = linux
I'm not sure about that :see_no_evil: The latest diff on GH hasn't changed

2021-08-10 09:50 UTC, sveba commented on Makefile
> +#build: export GOOS = linux
sorry about that. Now it should be fixed

2021-08-10 09:58 UTC, ccremer approved these changes
Thanks for the work!
Do you know if you are going to work on the parallelization right away or would you like a prerelease first?

2021-08-10 10:00 UTC, merged

2021-08-10 10:36 UTC, sveba commented
> Thanks for the work!
> Do you know if you are going to work on the parallelization right away or would you like a prerelease first?

I'm leaving in vacation for 1,5 months so I would not be able to work on this for that time. After that no problem. 
About release: like I said, this is your baby, you can decide. I have the exporter running on my server so I'm not in a hurry. :)

2021-08-10 11:03 UTC, ccremer commented
Ah ok. I'll wait for a release and try to come up with something, shouldn't be too hard.
Enjoy your vacation and thanks again for your contribution!

2021-08-10 11:06 UTC, sveba commented
Na klar. Habe ich gerne gemacht. Wie gesagt, bin absoluter Go-Anfänger ;)